stages:
  - test
  - build

test:
  stage: test
  image: python:3.12

  services:
    - name: postgres:16
      alias: postgres

  variables:
    DB_NAME: backupdb
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_HOST: postgres
    DB_PORT: "5432"
    SECRET_KEY: "test"
    DEBUG: "True"

  before_script:
    - pip install -r requirements.txt

  script:
    - python manage.py migrate
    - python manage.py test backups core users


build:
  stage: build
  image: docker:24

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker build -t backup-service .