stages:
  - test
  - build
  - deploy

variables:
  POSTGRES_DB: backupdb
  POSTGRES_USER: backupuser
  POSTGRES_PASSWORD: backuppass

  DB_HOST: postgres
  DB_NAME: backupdb
  DB_USER: backupuser
  DB_PASSWORD: backuppass
  DB_PORT: "5432"

  SECRET_KEY: "ci-only-secret-key-12345"

  IMAGE_NAME: backup-service

services:
  - name: postgres:16
    alias: postgres

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python manage.py migrate
    - pytest


build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $IMAGE_NAME:latest .


deploy:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client

  script:
    - scp image.tar dv@192.168.1.233:/home/dv/

    - ssh dv@192.168.1.233 "
        docker load < /home/dv/image.tar &&
        docker stop app || true &&
        docker rm app || true &&
        docker run -d --name app -p 8000:8000 backup-service:latest
      "

  only:
    - main