# Generated by Django 6.0.4 on 2026-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
